/* eslint-disable */
// Generated by Wrangler by running `wrangler types workers/control-api/src/worker-configuration.d.ts --include-runtime false --config workers/control-api/wrangler.toml` (hash: 158443bed6fe657b8f0822efe660defd)
interface __BaseEnv_Env {
	SCAS_CONFIG: KVNamespace;
	SCAS_KNOWLEDGE_BUCKET: R2Bucket;
	SCAS_MEMORY_BUCKET: R2Bucket;
	SCAS_CONTROL_DB: D1Database;
	SCAS_KNOWLEDGE_INDEX: VectorizeIndex;
	SCAS_MEMORY_INDEX: VectorizeIndex;
	ENVIRONMENT: "dev";
	AI_GATEWAY_ACCOUNT_ID: "unset";
	AI_GATEWAY_ID: "default";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "AI_GATEWAY_ACCOUNT_ID" | "AI_GATEWAY_ID">> {}
}
