/* eslint-disable */
// Generated by Wrangler by running `wrangler types workers/control-api/src/worker-configuration.d.ts --include-runtime false --config workers/control-api/wrangler.toml` (hash: ef3103bd22fed535b02261f11f1af5a6)
interface __BaseEnv_Env {
	SCAS_CONFIG: KVNamespace;
	SCAS_KNOWLEDGE_BUCKET: R2Bucket;
	SCAS_MEMORY_BUCKET: R2Bucket;
	SCAS_CONTROL_DB: D1Database;
	SCAS_KNOWLEDGE_INDEX: VectorizeIndex;
	SCAS_MEMORY_INDEX: VectorizeIndex;
	SCAS_INGEST_QUEUE: Queue;
	ENVIRONMENT: "staging" | "prod" | "dev";
	AI_GATEWAY_ACCOUNT_ID: "unset";
	AI_GATEWAY_ID: "scas-ai-gateway-staging-run" | "scas-ai-gateway-prod-run" | "scas-ai-gateway-dev-run";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface StagingEnv {
		SCAS_CONFIG: KVNamespace;
		SCAS_KNOWLEDGE_BUCKET: R2Bucket;
		SCAS_MEMORY_BUCKET: R2Bucket;
		SCAS_CONTROL_DB: D1Database;
		SCAS_KNOWLEDGE_INDEX: VectorizeIndex;
		SCAS_MEMORY_INDEX: VectorizeIndex;
		SCAS_INGEST_QUEUE: Queue;
		ENVIRONMENT: "staging";
		AI_GATEWAY_ACCOUNT_ID: "unset";
		AI_GATEWAY_ID: "scas-ai-gateway-staging-run";
	}
	interface ProdEnv {
		SCAS_CONFIG: KVNamespace;
		SCAS_KNOWLEDGE_BUCKET: R2Bucket;
		SCAS_MEMORY_BUCKET: R2Bucket;
		SCAS_CONTROL_DB: D1Database;
		SCAS_KNOWLEDGE_INDEX: VectorizeIndex;
		SCAS_MEMORY_INDEX: VectorizeIndex;
		SCAS_INGEST_QUEUE: Queue;
		ENVIRONMENT: "prod";
		AI_GATEWAY_ACCOUNT_ID: "unset";
		AI_GATEWAY_ID: "scas-ai-gateway-prod-run";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "AI_GATEWAY_ACCOUNT_ID" | "AI_GATEWAY_ID">> {}
}
