import type { TenantWorkbenchDefinition } from "./index";

export const khhTenantWorkbenchDefinition = {
  scope: {
    tenantId: "tenant_kinderhaus",
    areaId: "kinderhaus-heuschrecken",
  },
  hero: {
    title: "Leitungs-Cockpit",
    functionText:
      "Tageslage, Fristen, Personalrisiken, Dienste und Entwicklung schnell einordnen.",
  },
  navigation: [
    {
      routeId: "today",
      href: "/",
      label: "Heute",
      iconId: "layout-dashboard",
      privacyClass: "operational-summary",
    },
    {
      routeId: "deadlines",
      sectionId: "deadlines",
      href: "/fristen",
      label: "Fristen",
      iconId: "calendar-clock",
      privacyClass: "document-reference",
    },
    {
      routeId: "staffing",
      sectionId: "staffing",
      href: "/personal",
      label: "Personal-Ampel",
      iconId: "users-round",
      privacyClass: "person-reference-minimal",
    },
    {
      routeId: "services",
      sectionId: "services",
      href: "/dienste",
      label: "Dienste",
      iconId: "heart-handshake",
      privacyClass: "operational-summary",
    },
    {
      routeId: "cases",
      sectionId: "cases",
      href: "/vorgaenge",
      label: "Vorgaenge",
      iconId: "shield-check",
      privacyClass: "protected-case-summary",
    },
    {
      routeId: "occupancy",
      sectionId: "occupancy",
      href: "/belegung",
      label: "Belegung",
      iconId: "home",
      privacyClass: "person-reference-minimal",
    },
    {
      routeId: "development",
      sectionId: "development",
      href: "/entwicklung",
      label: "Entwicklung",
      iconId: "sparkles",
      privacyClass: "operational-summary",
    },
    {
      routeId: "documents",
      sectionId: "documents",
      href: "/dokumente",
      label: "Dokumente",
      iconId: "file-text",
      privacyClass: "document-reference",
    },
    {
      routeId: "tasks",
      sectionId: "tasks",
      href: "/aufgaben",
      label: "Aufgaben",
      iconId: "list-checks",
      privacyClass: "operational-summary",
    },
  ],
  dailySignals: [
    {
      signalId: "staffing-afternoon-reserve",
      title: "Personal",
      status: "pruefen",
      detail: "Nachmittag ohne Reserve geplant.",
      action: "Vertretung pruefen",
      iconId: "users-round",
      tone: "warning",
      privacyClass: "person-reference-minimal",
    },
    {
      signalId: "deadline-weekly-evidence",
      title: "Fristen",
      status: "kritisch",
      detail: "2 Nachweise laufen diese Woche ab.",
      action: "Nachweise oeffnen",
      iconId: "calendar-clock",
      tone: "danger",
      privacyClass: "document-reference",
    },
    {
      signalId: "service-kitchen-duty",
      title: "Kochdienst",
      status: "ok",
      detail: "Dienst bestaetigt, Hinweis vorhanden.",
      action: "Originalunterlage pruefen",
      iconId: "heart-handshake",
      tone: "success",
      privacyClass: "operational-summary",
    },
    {
      signalId: "case-leadership-follow-up",
      title: "Vorgaenge",
      status: "offen",
      detail: "1 Wiedervorlage braucht Leitungssicht.",
      action: "Vorgang ansehen",
      iconId: "shield-check",
      tone: "info",
      privacyClass: "protected-case-summary",
    },
  ],
  quickActions: [
    {
      actionId: "capture-case",
      title: "Vorgang erfassen",
      detail: "Minimalen Bezug, Risiko, Frist und Freigabestatus aufnehmen.",
      href: "/vorgaenge",
      cta: "Erfassen",
      iconId: "clipboard-check",
      privacyClass: "protected-case-summary",
    },
    {
      actionId: "review-evidence",
      title: "Nachweis pruefen",
      detail: "Gueltigkeit, Verantwortlichkeit und naechste Aktion klaeren.",
      href: "/fristen",
      cta: "Pruefen",
      iconId: "calendar-clock",
      privacyClass: "document-reference",
    },
    {
      actionId: "replace-duty",
      title: "Dienst ersetzen",
      detail: "Kochdienst oder Arbeitseinsatz mit Belehrungsstatus absichern.",
      href: "/dienste",
      cta: "Oeffnen",
      iconId: "heart-handshake",
      privacyClass: "operational-summary",
    },
  ],
  sections: {
    deadlines: {
      sectionId: "deadlines",
      routeId: "deadlines",
      title: "Fristen",
      subtitle: "Nachweise, Belehrungen und Wiedervorlagen nach Risiko steuern.",
      iconId: "calendar-clock",
      items: [
        "Erweitertes Fuehrungszeugnis, Erste Hilfe, IfSG und Lebensmittelbelehrung",
        "Status: gueltig, laeuft bald ab, fehlt, unklar oder nicht erforderlich",
        "Bezug nur als Vorname, Kuerzel, Rolle oder interne Referenz",
      ],
      focus: ["Nachweis", "Bereich", "Status", "Faellig", "Naechste Aktion"],
      privacyClass: "document-reference",
    },
    staffing: {
      sectionId: "staffing",
      routeId: "staffing",
      title: "Personal-Ampel",
      subtitle: "Tages- und Wochenrisiken fuer Mindestbesetzung sichtbar machen.",
      iconId: "users-round",
      items: [
        "Vormittag, Nachmittag, morgen und Risikotage getrennt bewerten",
        "PiA, FSJ und Praktikum nicht wie voll anrechenbare Fachkraefte behandeln",
        "Abwesenheiten ohne medizinische Details anzeigen",
      ],
      focus: ["Zeitfenster", "Ampel", "Reserve", "Risiko", "Vertretung"],
      privacyClass: "person-reference-minimal",
    },
    services: {
      sectionId: "services",
      routeId: "services",
      title: "Dienste",
      subtitle: "Kochdienste, Arbeitseinsaetze und Elternpflichten absichern.",
      iconId: "heart-handshake",
      items: [
        "Dienststatus fuer heute und morgen schnell erfassen",
        "Belehrungsstatus und Ersatzbedarf sichtbar machen",
        "Ernaehrungshinweise nur als knapper Status, nie als Detailakte",
      ],
      focus: ["Dienst", "Status", "Hinweis", "Ersatz", "Aktion"],
      privacyClass: "operational-summary",
    },
    cases: {
      sectionId: "cases",
      routeId: "cases",
      title: "Vorgaenge",
      subtitle: "Sensible Vorgaenge getrennt von normalem Aufgaben-Kanban fuehren.",
      iconId: "shield-check",
      items: [
        "Vorfall, Unfall, Kinderschutz und Beschwerde sauber trennen",
        "Agent darf strukturieren, aber keine finale Bewertung treffen",
        "Meldungen an Jugendamt, KVJS oder Gesundheitsamt nur nach Freigabe",
      ],
      focus: ["Typ", "Risiko", "Freigabe", "Wiedervorlage", "Schutzbereich"],
      privacyClass: "protected-case-summary",
    },
    occupancy: {
      sectionId: "occupancy",
      routeId: "occupancy",
      title: "Belegung",
      subtitle: "U3, Kindergarten und Hort mit Uebergaengen planen.",
      iconId: "home",
      items: [
        "Kita-Portal-Status nur als Prozessstatus fuehren",
        "Uebergang U3, Kindergarten, Schule und Hort in Monatslogik planen",
        "Geschwister- oder Prioritaetsmerkmale ohne Familienakte erfassen",
      ],
      focus: ["Bereich", "Monat", "Plaetze", "Uebergang", "Risiko"],
      privacyClass: "person-reference-minimal",
    },
    development: {
      sectionId: "development",
      routeId: "development",
      title: "Entwicklung",
      subtitle: "Paedagogik, Team, Raeume und Elterninitiative systematisch verbessern.",
      iconId: "sparkles",
      items: [
        "Jahresziele und Quartalsmassnahmen sichtbar halten",
        "Qualitaetsreviews als Lernsystem, nicht als Kontrollinstrument nutzen",
        "Ideen aus Team und Elternschaft in kleine Experimente fuehren",
      ],
      focus: ["Ziel", "Massnahme", "Review", "Verantwortung", "Wirkung"],
      privacyClass: "operational-summary",
    },
    documents: {
      sectionId: "documents",
      routeId: "documents",
      title: "Dokumente",
      subtitle: "Vorlagen, Konzepte und Nachweise mit Status und Version fuehren.",
      iconId: "file-text",
      items: [
        "Betriebserlaubnis, Konzeption, Schutzkonzept und Hygieneplan referenzieren",
        "Dokumente mit Version, Gueltigkeit und Verantwortlichkeit versehen",
        "Originalunterlagen bleiben ausserhalb der Standarduebersichten",
      ],
      focus: ["Dokument", "Version", "Status", "Gueltig bis", "Verantwortung"],
      privacyClass: "document-reference",
    },
    tasks: {
      sectionId: "tasks",
      routeId: "tasks",
      title: "Aufgaben",
      subtitle: "Kanban nur als Arbeitsschicht ueber Fristen, Nachweisen und Vorgaengen.",
      iconId: "list-checks",
      items: [
        "Status: Neu, Geplant, In Arbeit, Wartet, Zur Pruefung, Erledigt",
        "Jede Aufgabe braucht Bereich, Frist, Risiko und Verantwortung",
        "Freigabe- und Nachweispflichten direkt sichtbar machen",
      ],
      focus: ["Aufgabe", "Bereich", "Frist", "Risiko", "Status"],
      privacyClass: "operational-summary",
    },
  },
  privacyRules: [
    "Keine vollstaendigen Kinder-, Eltern- oder Personalstammdaten",
    "Personenbezug nur mit Vorname, Kuerzel oder interner Referenz",
    "Keine Adressen, privaten Kontaktdaten, Geburtsdaten oder Vertragsdaten",
    "Gesundheits- und Sorgerechtshinweise nur als minimaler Status",
  ],
} as const satisfies TenantWorkbenchDefinition;

export const khhSectionAliases = {
  fristen: "deadlines",
  personal: "staffing",
  dienste: "services",
  vorgaenge: "cases",
  belegung: "occupancy",
  entwicklung: "development",
  dokumente: "documents",
  aufgaben: "tasks",
} as const;

export type KhhSectionSlug = keyof typeof khhSectionAliases;
